channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip=20.2.4
  - albumentations=0.5.2
  - cudatoolkit=10.2
  - cudnn=7.6.5
  - imgaug=0.4.0
  - matplotlib=3.3.2
  - pandas=1.1.3
  - python=3.8.3
  - scikit-learn=0.23.2

  - pip:
      - numpy==1.20
      - tensorflow-gpu==2.4.1
      - azureml-sdk==1.29.0
      - imagehash==4.2.1
      - image-classifiers==1.0.0
      - tqdm==4.62.2
      - opencv-python==4.2.0.34 
      - tensorflow-addons==0.12.1
      - tf-keras-vis
      - optuna
