# ------------------------------------- Base arguments ------------------------------------- #
subscription: 15c1afea-319d-4e83-874a-8c989125f3b9

resource_group: rg-dss-playground

experiment: anonymisation-classification

workspace: ml-playground

environment: classifier

docker_image: azureml/azureml_976b98f8b8753df3e1098b820ca78c22:latest

#container registry in the workspace
#for private containers specify username and password
container_registry: 
  address: 1b25a665dcb5497a8abbc94e1eb67efb.azurecr.io
  #username:
  #password:


datastore: kzsdpstage

dataset: ../endo_out_binary_v2/testset
#help="Directory of training or testing data"

output: ../model_generator_results/interpret
#help="Output Directory of training or testing"

saved_model: ../model_generator_results/train/models/20220627-100737
#help="Directory of the saved model. Used for test.py",
#default=""

#check_data: True
#help="Check if all samples in dataset can be processed",
#action='store_true'
#default= False

# ------------------------------------- Interpretability ------------------------------------- #
baseline: black
#help="Baseline used in integrated gradients",
#choices=['black', 'white', 'random', 'mean'],
#default='black')

interpreter: smoothgrad
#help="Interpretability method",
#choices=['ig', 'gradcam', 'gradcam++', 'smoothgrad'],
#default='ig')

cmap: inferno
#help='Colormap for heatmap',
#default='inferno')

overlay_alpha: 0.4
#type=float,
#default=0.4)
