# ------------------------------------- Base arguments ------------------------------------- #
subscription: 

resource_group: 

experiment: anonymisation-classification

workspace: 

environment: classifier

docker_image: 

#container registry in the workspace
#for private containers specify username and password
container_registry: 
  address: 
  #username:
  #password:


datastore: kzsdpstage

dataset: endo_out_binary_v2/testset
#help="Directory of training or testing data"

output: model_generator_results/interpret
#help="Output Directory of training or testing"

saved_model: model_generator_results/models/20220627-100737
#help="Directory of the saved model. Used for test.py",
#default=""

#check_data: True
#help="Check if all samples in dataset can be processed",
#action='store_true'
#default= False

# ------------------------------------- Interpretability ------------------------------------- #
baseline: black
#help="Baseline used in integrated gradients",
#choices=['black', 'white', 'random', 'mean'],
#default='black')

interpreter: smoothgrad
#help="Interpretability method",
#choices=['ig', 'gradcam', 'gradcam++', 'smoothgrad'],
#default='ig')

cmap: inferno
#help='Colormap for heatmap',
#default='inferno')

overlay_alpha: 0.4
#type=float,
#default=0.4)
