# ------------------------------------- Base arguments ------------------------------------- #
subscription: 15c1afea-319d-4e83-874a-8c989125f3b9

resource_group: rg-dss-playground

experiment: anonymisation-MCC

workspace: ml-playground

environment: classifier

docker_image: azureml/azureml_aa611e280d9bfe93f6623971723b9e7b:latest

#container registry in the workspace
#for private containers specify username and password
container_registry: 
  address: 1b25a665dcb5497a8abbc94e1eb67efb.azurecr.io
  #username:
  #password:

datastore: kzsdpstage

dataset: ../endo_out_binary_v2/testset
#help="Directory of training or testing data"

output: ../model_generator_results/test
#help="Output Directory of training or testing"

saved_model: ../model_generator_results/train/models/20220713-065638
#help="Directory of the saved model. Used for test.py",
#default=""

#check_data: True
#help="Check if all samples in dataset can be processed",
#action='store_true'
#default= False

class_names: ['00_safe', '01_critical']
#help="Define class names to include in plots and logs. e.g. --class_names 00_Out 01_In 02_no_sig",
#nargs='+')

# ------------------------------------- Testing arguments ------------------------------------- #

#bayesian: None
#help="dropout-rate for monte carlo dropout layers added before each trainable layer",
#type=float,
#default=None)

#bayesian_samples: 10
#help="number of bayesian samples to evaluate",
#type=int,
#default=10)

# for classification
#csv_eval: ''
#help="Path to demonstrator predictions .csv file to evaluate. More info in README.md",
#default='')

class_eval: True
#help="Evaluate classification model. More info in README.md",
#action='store_true')

#class_overlay: True
#help="Overlay classification samples with the output probability",
#action='store_true')

#class_table: True
#help="Output a csv file with sample names, gts, predictions and prediction probabilities",
#action='store_true')

#class_sort: True
#help="Sort classifier predictions according to class names",
#action='store_true')

#temp_filter: True
#help="Activate weighted-mean temporal filtering and set type",
#action='store_true')

#filter_size: 10
#help="Size of buffer for temporal filtering",
#type=int,
#default=10)

#state_filter: cholec80
#help="Activate state machinephase transition. Give in the name of the dataset",
#choices=['', 'cholec80'],
#default='')

# ------------------------------------- Plotting parameters ------------------------------------- #
#plot: ''
#help="type of plot to be generated",
#choices=['', 'cm', 'line', 'prob', 'bbox'],
#default='')

