
# ------------------------------------- Base arguments ------------------------------------- #
subscription: 15c1afea-319d-4e83-874a-8c989125f3b9

resource_group: rg-dss-playground

experiment: optuna-mlflow

workspace: ml-playground

environment: classifier

docker_image: azureml/azureml_baa3acfa3b725dede706d62f17962ce5:latest

#container registry in the workspace
#for private containers specify username and password
container_registry: 
  address: 1b25a665dcb5497a8abbc94e1eb67efb.azurecr.io
  #username:
  #password:

datastore: kzsdpstage

dataset: DRV/Anonymization/Besucherzentrum_Out_Seqs/endo_out_binary_v2/trainset
#help="Directory of training or testing data"

output: MOD/model_generator_results/train
#help="Output Directory of training or testing"

#valdata:
#help="Directory of validation data. If not defined data will be split into train+val"

#azureml_mlflow_uri : azureml://westeurope.api.azureml.ms/mlflow/v1.0/subscriptions/15c1afea-319d-4e83-874a-8c989125f3b9/resourceGroups/rg-dss-playground/providers/Microsoft.MachineLearningServices/workspaces/ml-playground

optuna_trials: 10
##help="Optuna trials number"
#type=int
#default=10

dim: 224
#help="Dimensions of input images after preprocessing (NxN). The user can also input a list of dimensions [H, B]",
#type=int or list,
#default=224)

resize: center-crop
#help="Type of resizing for classification and segmentation,For detection, its fixed at pad resizing",
#choices=['center-crop', 'padding', 'downscale'],
#default='center-crop'

#check_data: True
#help="Check if all samples in dataset can be processed",
#action='store_true'
#default= False

class_names: ['00_safe', '01_critical']
#help="Define class names to include in plots and logs. e.g. --class_names 00_Out 01_In 02_no_sig",
#nargs='+')

#model_name:
#help="Name of the model to register in Azure ML",
#default=""

#commit_hash: ''
#help="Git commit hash attributed to the current repository. !! automatically filled !! ",
#default=""


# ------------------------------------- Model arguments ------------------------------------- #
backbone: ResNet50
#help="Name of the model's backbone",
#choices=['MobileNet', 'MobileNetV2', 'Xception', 'NASNetMobile', 'DenseNet121', 'DarkNet',
         #'ResNet18', 'ResNet34', 'ResNet50', 'ResNeXt50', 'ResNet50V2',
         #'SEResNet18', 'SEResNet34', 'SEResNet50', 'SEResNeXt50',
         #'EfficientNetB0', 'EfficientNetB1', 'EfficientNetB2', 'EfficientNetB3',
         #'EfficientNetB4', 'EfficientNetB5', 'EfficientNetB6', 'EfficientNetB7'],
#default='')

num_classes: 2
#type=int,
#default=2)

#num_labels: 0
#help="Specify number of labels. ONLY for multi-label classification",
#type=int,
#default=0)

# ------------------------------------- Training arguments ------------------------------------- #
#epochs: 10 #optuna
#help="Number of training epochs",
#type=int,
#default=10)

#batch: 16 #optuna
#help="Batch size",
#type=int,
#default=16)

validation_split: 0.25
#type=float,
#default=0.1)

#lr: 0.001 #optuna
#help="Initial learning rate for Adam optimizer",
#type=float,
#default=0.001)

#lr_decay: False
#help="Learning rate step decay for Adam optimizer",
#action='store_true')

dropout: 0.25
#help="dropout rate on the classifiers' densly connected head",
#type=float,
#default=0)

#label_smoothing: False
#help="Smooth labels for binary/multi-class classification",
#action='store_true')

#train_backbone: False
#help="Train encoder parameters",
#action='store_true')

#kmeans: False
#help="Apply k-means clustering on a dataset of bounding boxes to generate custom anchors",
#action='store_true')

#bayesian: None
#help="dropout-rate for monte carlo dropout layers added before each trainable layer",
#type=float,
#default=None)

#bayesian_samples: 10
#help="number of bayesian samples to evaluate",
#type=int,
#default=10)